services:

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"  # REST API
      - "3002:3002"  # Socket
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3001"
    environment:
      REACT_APP_API_URL: http://backend:3000
      REACT_APP_SOCKET_URL: http://backend:3002
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

